name: Monitor 1-click Deployment

permissions: {}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'prod'
        type: choice
        options:
          - stage
          - prod
          - dev
      originalImageTag:
        description: 'The original image tag that has been deployed'
        required: true
        type: string
        pattern: '^[a-f0-9]{7,12}$'
jobs:
  pull_retag_push:
    name: Pull, Retag, and Push Images
    runs-on: ubuntu-latest
    environment: build
    permissions:
      contents: "read" # Needed for checkout
      id-token: "write" # Needed for GCP auth
      packages: "none" # Explicitly disable package permissions
    env:
      GAR_IMAGE_BASE: ${{ vars.GAR_REPO }}/${{ github.event.repository.name }}
      GAR_REGISTRY: us-docker.pkg.dev # Define GAR registry hostname
      DOCKERHUB_IMAGE: mozilla/blurts-server # Define Docker Hub image name
      SAFE_IMAGE_TAG: ${{ inputs.originalImageTag }}
      SAFE_ENVIRONMENT: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Pull Docker Hub image
        run: docker pull "${{ env.DOCKERHUB_IMAGE }}:${{ env.SAFE_IMAGE_TAG }}"

      - name: Retag Docker Hub image
        run: docker tag "${{ env.DOCKERHUB_IMAGE }}:${{ env.SAFE_IMAGE_TAG }}" "${{ env.DOCKERHUB_IMAGE }}:${{ env.SAFE_ENVIRONMENT }}-${{ env.SAFE_IMAGE_TAG }}"

      - name: Push Docker Hub image
        run: docker push "${{ env.DOCKERHUB_IMAGE }}:${{ env.SAFE_ENVIRONMENT }}-${{ env.SAFE_IMAGE_TAG }}"

      - name: Pull GAR image
        run: docker pull "${{ env.GAR_IMAGE_BASE }}:${{ env.SAFE_IMAGE_TAG }}"

      - name: Retag GAR image
        run: docker tag "${{ env.GAR_IMAGE_BASE }}:${{ env.SAFE_IMAGE_TAG }}" "${{ env.GAR_IMAGE_BASE }}:${{ env.SAFE_ENVIRONMENT }}-${{ env.SAFE_IMAGE_TAG }}"

      - name: Push GAR image
        run: docker push "${{ env.GAR_IMAGE_BASE }}:${{ env.SAFE_ENVIRONMENT }}-${{ env.SAFE_IMAGE_TAG }}"
