name: Daily Pre-release

permissions: {}

on:
  workflow_dispatch: # Allows manual trigger if needed

jobs:
  create-pre-release:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    environment: build
    env:
      GAR_IMAGE_BASE: ${{ vars.GAR_REPO }}/${{ github.event.repository.name }}
      GAR_REGISTRY: us-docker.pkg.dev
      DOCKERHUB_IMAGE: mozilla/blurts-server # Define Docker Hub image name
      VERSION: ${{ steps.meta.outputs.version }}
      TAGS: ${{ steps.meta.outputs.tags }}

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v5
      with:
        ref: main
        persist-credentials: false

    - name: Get current date
      run: |
        echo "CURRENT_DATE=$(date +%Y.%m.%d)" >> $GITHUB_ENV
        echo "tag_name: $(date +%Y.%m.%d)"

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKERHUB_IMAGE }}
        tags: type=sha,format=short,prefix=

    - name: Pull Docker image from GAR with commit tag
      run: |
        echo "docker pull ${{ env.GAR_IMAGE_BASE }}:$VERSION"
        echo $TAGS

    - name: Tag Docker image for Docker Hub with release tag
      run: |
        echo "docker tag ${{ env.GAR_IMAGE_BASE }}:$VERSION ${{ env.DOCKERHUB_IMAGE }}:${{ env.CURRENT_DATE }}"
        echo $TAGS
    - name: Push Docker image to Docker Hub with release tag
      run: echo "docker push ${{ env.DOCKERHUB_IMAGE }}:${{ env.CURRENT_DATE }}"

    - name: Tag Docker image for GAR with release tag
      run: echo "docker tag ${{ env.GAR_IMAGE_BASE }}:$VERSION ${{ env.GAR_IMAGE_BASE }}:${{ env.CURRENT_DATE }}"

    - name: Push Docker image to GAR with release tag
      run: echo "docker push ${{ env.GAR_IMAGE_BASE }}:${{ env.CURRENT_DATE }}"
